baseurl = "https://marlin-na.github.io/r-api/"
languageCode = "en-us"
#metadataformat = "yaml"
title = "R's C API"
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = ""

[params]
	name = "R's C API"
	description = "Documentation for R's internal C API"

	github_user   = "marlin-na"
	github_repo   = "r-api"
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"


	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	#copyright = "[Digitalcraftsman](https://github.com/digitalcraftsman)"
	show_powered_by = true
